apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: quay-push-binding
spec:
  params:
    - name: agent-image
      value: $(body.docker_url)
    - name: agent-tag
      value: $(extensions.agent_tag)
