apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: submission-binding
spec:
  params:
    - name: repo-url
      value: $(body.repository.clone_url)
    - name: revision
      value: $(body.pull_request.head.sha)
    - name: repo-name
      value: $(body.repository.full_name)
    - name: submission-dir
      value: $(extensions.submission_directory)
    - name: pr-number
      value: $(body.pull_request.number)
